export interface BlackCard {
  id: string;
  text: string;
  pick: number;
}

export interface WhiteCard {
  id: string;
  text: string;
}

export const BLACK_CARDS: BlackCard[] = [
  { id: 'b1', text: '_ is the new _.',  pick: 2 },
  { id: 'b2', text: "Why can't I sleep at night?", pick: 1 },
  { id: 'b3', text: "I got 99 problems but _ ain't one.", pick: 1 },
  { id: 'b4', text: "What's that smell?", pick: 1 },
  { id: 'b5', text: "I never truly lived until I discovered _.", pick: 1 },
  { id: 'b6', text: "In a world ravaged by _, our only solace is _.", pick: 2 },
  { id: 'b7', text: "During sex, I like to think about _.", pick: 1 },
  { id: 'b8', text: "What is Batman's guilty pleasure?", pick: 1 },
  { id: 'b9', text: "_ + _ = _.", pick: 3 },
  { id: 'b10', text: "What ended my last relationship?", pick: 1 },
  { id: 'b11', text: "TSA guidelines now prohibit _ on airplanes.", pick: 1 },
  { id: 'b12', text: "What's a girl's best friend?", pick: 1 },
  { id: 'b13', text: "The class field trip was completely ruined by _.", pick: 1 },
  { id: 'b14', text: "When I am president, I will create the Department of _.", pick: 1 },
  { id: 'b15', text: "_ is a slippery slope that leads to _.", pick: 2 },
  { id: 'b16', text: "What's the next Happy Meal toy?", pick: 1 },
  { id: 'b17', text: "Alternative medicine is now embracing the curative powers of _.", pick: 1 },
  { id: 'b18', text: "And the Academy Award for _ goes to _.", pick: 2 },
  { id: 'b19', text: "But before I kill you, Mr. Bond, I must show you _.", pick: 1 },
  { id: 'b20', text: "Coming to Broadway this season, _: The Musical.", pick: 1 },
  { id: 'b21', text: "Dude, don't touch my _.", pick: 1 },
  { id: 'b22', text: "For my next trick, I will pull _ out of _.", pick: 2 },
  { id: 'b23', text: "I drink to forget _.", pick: 1 },
  { id: 'b24', text: "I'm sorry Professor, but I couldn't complete my homework because of _.", pick: 1 },
  { id: 'b25', text: "Instead of coal, Santa now gives the bad children _.", pick: 1 },
  { id: 'b26', text: "Life for Native Americans was forever changed when the White Man introduced them to _.", pick: 1 },
  { id: 'b27', text: "Next on ESPN2, the World Series of _.", pick: 1 },
  { id: 'b28', text: "Step 1: _. Step 2: _. Step 3: Profit.", pick: 2 },
  { id: 'b29', text: "Studies show that lab rats navigate mazes 50% faster after being exposed to _.", pick: 1 },
  { id: 'b30', text: "The healing process began when I told my therapist about _.", pick: 1 },
  { id: 'b31', text: "This is the way the world ends. Not with a bang but with _.", pick: 1 },
  { id: 'b32', text: "War! What is it good for?", pick: 1 },
  { id: 'b33', text: "What are my parents hiding from me?", pick: 1 },
  { id: 'b34', text: "What do old people smell like?", pick: 1 },
  { id: 'b35', text: "What helps Obama unwind?", pick: 1 },
  { id: 'b36', text: "What will always get you laid?", pick: 1 },
  { id: 'b37', text: "What will I bring back in time to convince people that I am a powerful wizard?", pick: 1 },
  { id: 'b38', text: "What's the crustiest?", pick: 1 },
  { id: 'b39', text: "When Pharaoh remained unmoved, Moses called down a plague of _.", pick: 1 },
  { id: 'b40', text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate _.", pick: 1 },
];

export const WHITE_CARDS: WhiteCard[] = [
  { id: 'w1', text: 'Being on fire.' },
  { id: 'w2', text: 'Racism.' },
  { id: 'w3', text: 'Old-people smell.' },
  { id: 'w4', text: 'A micropenis.' },
  { id: 'w5', text: 'Women in yogurt commercials.' },
  { id: 'w6', text: 'Classist undertones.' },
  { id: 'w7', text: 'Not giving a shit about the Third World.' },
  { id: 'w8', text: 'Coat hanger abortions.' },
  { id: 'w9', text: 'The Rapture.' },
  { id: 'w10', text: 'Being a motherfucking sorcerer.' },
  { id: 'w11', text: 'A Bop It.' },
  { id: 'w12', text: 'A cooler full of organs.' },
  { id: 'w13', text: 'A lifetime of sadness.' },
  { id: 'w14', text: 'A man in yoga pants with a ponytail and feathered earrings.' },
  { id: 'w15', text: 'A mopey zoo lion.' },
  { id: 'w16', text: 'A murder most foul.' },
  { id: 'w17', text: 'A salty surprise.' },
  { id: 'w18', text: 'A snapping turtle biting the tip of your penis.' },
  { id: 'w19', text: 'A windmill full of corpses.' },
  { id: 'w20', text: 'All-you-can-eat shrimp for $4.99.' },
  { id: 'w21', text: 'An Oedipus complex.' },
  { id: 'w22', text: 'Auschwitz.' },
  { id: 'w23', text: 'Battlefield amputations.' },
  { id: 'w24', text: 'Britney Spears at 55.' },
  { id: 'w25', text: 'Burping.' },
  { id: 'w26', text: 'Crippling debt.' },
  { id: 'w27', text: 'Daddy issues.' },
  { id: 'w28', text: 'Dead babies.' },
  { id: 'w29', text: 'Estrogen.' },
  { id: 'w30', text: 'Ethnic cleansing.' },
  { id: 'w31', text: 'Explosions.' },
  { id: 'w32', text: 'Famine.' },
  { id: 'w33', text: 'Farting and walking away.' },
  { id: 'w34', text: 'Flash mobs.' },
  { id: 'w35', text: 'Flying sex snakes.' },
  { id: 'w36', text: 'Friend zone.' },
  { id: 'w37', text: 'German dungeon porn.' },
  { id: 'w38', text: 'Getting drunk on mouthwash.' },
  { id: 'w39', text: 'Gloryholes.' },
  { id: 'w40', text: 'Grandma.' },
  { id: 'w41', text: 'Harry Potter erotica.' },
  { id: 'w42', text: 'Heartwarming orphans.' },
  { id: 'w43', text: 'Hot Pockets.' },
  { id: 'w44', text: 'Incest.' },
  { id: 'w45', text: 'Kanye West.' },
  { id: 'w46', text: 'Licking things to claim them as your own.' },
  { id: 'w47', text: 'Loud chewing.' },
  { id: 'w48', text: 'Meth.' },
  { id: 'w49', text: 'Mouth herpes.' },
  { id: 'w50', text: 'My collection of high-tech sex toys.' },
  { id: 'w51', text: 'My inner demons.' },
  { id: 'w52', text: 'My sex life.' },
  { id: 'w53', text: 'Nicolas Cage.' },
  { id: 'w54', text: 'Nipple blades.' },
  { id: 'w55', text: 'Obesity.' },
  { id: 'w56', text: 'Passive-aggressive Post-it notes.' },
  { id: 'w57', text: 'Pedophiles.' },
  { id: 'w58', text: 'Picking up girls at the abortion clinic.' },
  { id: 'w59', text: 'Poor life choices.' },
  { id: 'w60', text: 'Puberty.' },
  { id: 'w61', text: 'Road kill.' },
  { id: 'w62', text: 'Roofies.' },
  { id: 'w63', text: 'Sean Connery.' },
  { id: 'w64', text: 'Sexting.' },
  { id: 'w65', text: 'Sniffing glue.' },
  { id: 'w66', text: 'Soup that is too hot.' },
  { id: 'w67', text: 'Stranger danger.' },
  { id: 'w68', text: 'Sweet, sweet vengeance.' },
  { id: 'w69', text: 'Synergistic management solutions.' },
  { id: 'w70', text: 'The American Dream.' },
  { id: 'w71', text: 'The Bible.' },
  { id: 'w72', text: 'The blood of Christ.' },
  { id: 'w73', text: 'The Force.' },
  { id: 'w74', text: 'The heart of a child.' },
  { id: 'w75', text: 'The miracle of childbirth.' },
  { id: 'w76', text: 'The placenta.' },
  { id: 'w77', text: 'The Three-Fifths Compromise.' },
  { id: 'w78', text: 'Dying.' },
  { id: 'w79', text: 'Vigilante justice.' },
  { id: 'w80', text: 'Whipping it out.' },
  { id: 'w81', text: 'Wiping her butt.' },
  { id: 'w82', text: 'A bleached asshole.' },
  { id: 'w83', text: 'Full-frontal nudity.' },
  { id: 'w84', text: 'Lance Armstrong\'s missing testicle.' },
  { id: 'w85', text: 'Natural male enhancement.' },
  { id: 'w86', text: 'Tasteful sideboob.' },
  { id: 'w87', text: 'The token minority.' },
  { id: 'w88', text: 'Two midgets shitting into a bucket.' },
  { id: 'w89', text: 'Chunks of dead prostitute.' },
  { id: 'w90', text: 'A brain tumor.' },
  { id: 'w91', text: 'Figgy pudding.' },
  { id: 'w92', text: 'Aaron Burr.' },
  { id: 'w93', text: 'Amputees.' },
  { id: 'w94', text: 'A bag of magic beans.' },
  { id: 'w95', text: 'Science.' },
  { id: 'w96', text: 'A falcon with a cap on its head.' },
  { id: 'w97', text: 'A gassy antelope.' },
  { id: 'w98', text: 'Fear itself.' },
  { id: 'w99', text: 'Drunk texting.' },
  { id: 'w100', text: 'Chainsaws for hands.' },
];

export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function dealHand(deck: WhiteCard[], count: number): { hand: WhiteCard[]; remaining: WhiteCard[] } {
  const hand = deck.slice(0, count);
  const remaining = deck.slice(count);
  return { hand, remaining };
}
